### Create a new user
POST http://localhost:5229/users
Content-Type: application/json

{
  "username": "ali",
  "userAge": 30
}

###

### Get all users
GET http://localhost:5229/users

###

### Get a user by username
GET http://localhost:5229/users/ali

###

### Update a user by username
PUT http://localhost:5229/users/ali
Content-Type: application/json

{
  "username": "ali",
  "userAge": 31
}

###

### Delete a user by username
DELETE http://localhost:5229/users/ali